export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const FORGOT_PASSWORD_MODAL = 'FORGOT_PASSWORD_MODAL'
export const ADD_ITEM_MODAL = 'ADD_ITEM_MODAL'

export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS'
export const GET_ANNOUNCEMENT_DETAILS = 'GET_ANNOUNCEMENT_DETAILS'
export const ADD_ITEM = 'ADD_ITEM'
