export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const FORGOT_PASSWORD_MODAL = 'FORGOT_PASSWORD_MODAL'
export const ADD_ITEM_MODAL = 'ADD_ITEM_MODAL'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const EDIT_USER_DATA = 'EDIT_USER_DATA'

export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS'
export const GET_ANNOUNCEMENT_DETAILS = 'GET_ANNOUNCEMENT_DETAILS'
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT'
export const EDIT_ANNOUNCEMENT = 'EDIT_ANNOUNCEMENT'

export const GET_CATEGORIES = 'GET_CATEGORIES'

export const USER_SIGN_IN = 'USER_SIGN_IN'
export const USER_SIGN_OUT = 'USER_SIGN_OUT'
export const GET_USER_DATA = 'GET_USER_DATA'

export const GET_ITEMS = 'GET_ITEMS'
export const GET_ITEM_DETAILS = 'GET_ITEM_DETAILS'
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'

export const GET_DIVISIONS = 'GET_DIVISIONS'
